export const UPDATE_GAME = "UPDATE_GAME";
export const FETCH_MOVABLES = "FETCH_MOVABLES";
export const SELECT_CUBE_REPLY = "SELECT_CUBE_REPLY";
export const CREATE_GAME = "CREATE_GAME";
export const FETCH_TEAM_REPLY = "FETCH_TEAM_REPLY";
